### ISSUE TITLE
Hello, thank you very much for your work. Has it been published? We would like to use the code base for comparative experiments and would like to cite your work.

### ISSUE THREAD

**Issue by yuzhewen** [ZHANG-JiXiang/Lightweight-Transformer-for-fault-diagnosis#1]

**Comment by ZHANG-JiXiang** [comment]
您好
目前论文还在审稿中，但您可以其他算法代码供进行比较实验。




张吉祥
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ZHANG-JiXiang/Lightweight-Transformer-for-fault-diagnosis"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年10月29日(星期二) 上午10:51
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[ZHANG-JiXiang/Lightweight-Transformer-for-fault-diagnosis] Hello, thank you very much for your work. Has it been published? We would like to use the code base for comparative experiments and would like to cite your work. (Issue #1)
